In [4]:
import numpy as np

# Define the inputs as a list of lists
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

# Define the weights as a list of lists
weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]]

# Define the biases as a list
biases = [2, 3, 0.5]

# Perform matrix multiplication between inputs and weights,
# and add biases to each neuron.
output = np.dot(inputs, np.array(weights).T) + biases

# Print the output
print(output)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [15]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []

# Rectified linear activation
for i in inputs:
    if i > 0:
        output.append(max(0, i))

print(output)

[2, 3.3, 1.1, 2.2]


In [13]:
np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights with random values scaled by 0.10
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        # Initialize biases as zeros
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        # dot product of inputs and weights, then add biases
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

layer1 = Layer_Dense(4, 5) # 4 input neurons and 5 output neurons
layer2 = Layer_Dense(5, 2) # 5 input neurons (output from layer1) and 2 output neurons

layer1.forward(X)
layer2.forward(layer1.output)

# Print the output of the second layer
print(layer2.output)


[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
